package org.softgreen.organizacion.model;

// Generated 02-may-2014 11:48:28 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlElement;

/**
 * TransaccionCajaCaja generated by hbm2java
 */
@Entity
@Table(name = "TRANSACCION_CAJA_CAJA", schema = "BDSISTEMAFINANCIERO")
public class TransaccionCajaCaja implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private BigInteger idTransaccionCajaCaja;
	private Moneda moneda;
	private HistorialCaja historialCajaDestino;
	private HistorialCaja historialCajaOrigen;
	private Date fecha;
	private Date hora;
	private BigDecimal saldoDisponibleOrigen;
	private String observacion;
	private int estadoSolicitud;
	private int estadoConfirmacion;
	private BigDecimal saldoDisponibleDestino;
	private BigDecimal monto;

	public TransaccionCajaCaja() {
	}

	public TransaccionCajaCaja(BigInteger idTransaccionCajaCaja, HistorialCaja historialCajaDestino, HistorialCaja historialCajaOrigen, Date fecha, Date hora, BigDecimal saldoDisponibleOrigen, boolean estadoSolicitud, boolean estadoConfirmacion, BigDecimal saldoDisponibleDestino) {
		this.idTransaccionCajaCaja = idTransaccionCajaCaja;
		this.historialCajaDestino = historialCajaDestino;
		this.historialCajaOrigen = historialCajaOrigen;
		this.fecha = fecha;
		this.hora = hora;
		this.saldoDisponibleOrigen = saldoDisponibleOrigen;
		this.estadoSolicitud = (estadoSolicitud ? 1 : 0);
		this.estadoConfirmacion = (estadoConfirmacion ? 1 : 0);
		this.saldoDisponibleDestino = saldoDisponibleDestino;
	}

	public TransaccionCajaCaja(BigInteger idTransaccionCajaCaja, Moneda moneda, HistorialCaja historialCajaDestino, HistorialCaja historialCajaOrigen, Date fecha, Date hora, BigDecimal saldoDisponibleOrigen, String observacion, boolean estadoSolicitud, boolean estadoConfirmacion, BigDecimal saldoDisponibleDestino) {
		this.idTransaccionCajaCaja = idTransaccionCajaCaja;
		this.moneda = moneda;
		this.historialCajaDestino = historialCajaDestino;
		this.historialCajaOrigen = historialCajaOrigen;
		this.fecha = fecha;
		this.hora = hora;
		this.saldoDisponibleOrigen = saldoDisponibleOrigen;
		this.observacion = observacion;
		this.estadoSolicitud = (estadoSolicitud ? 1 : 0);
		this.estadoConfirmacion = (estadoConfirmacion ? 1 : 0);
		this.saldoDisponibleDestino = saldoDisponibleDestino;
	}

	@XmlElement(name = "id")
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Id
	@Column(name = "ID_TRANSACCION_CAJA_CAJA", unique = true, nullable = false, precision = 22, scale = 0)
	public BigInteger getIdTransaccionCajaCaja() {
		return this.idTransaccionCajaCaja;
	}

	public void setIdTransaccionCajaCaja(BigInteger idTransaccionCajaCaja) {
		this.idTransaccionCajaCaja = idTransaccionCajaCaja;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_MONEDA")
	public Moneda getMoneda() {
		return this.moneda;
	}

	public void setMoneda(Moneda moneda) {
		this.moneda = moneda;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_CAJA_HISTORIAL_DESTINO", nullable = false)
	public HistorialCaja getHistorialCajaDestino() {
		return this.historialCajaDestino;
	}

	public void setHistorialCajaDestino(HistorialCaja historialCajaDestino) {
		this.historialCajaDestino = historialCajaDestino;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_CAJA_HISTORIAL_ORIGEN", nullable = false)
	public HistorialCaja getHistorialCajaOrigen() {
		return this.historialCajaOrigen;
	}

	public void setHistorialCajaOrigen(HistorialCaja historialCajaOrigen) {
		this.historialCajaOrigen = historialCajaOrigen;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA", nullable = false, length = 7)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "HORA", nullable = false)
	public Date getHora() {
		return this.hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

	@Column(name = "SALDO_DISPONIBLE_ORIGEN", nullable = false, precision = 18)
	public BigDecimal getSaldoDisponibleOrigen() {
		return this.saldoDisponibleOrigen;
	}

	public void setSaldoDisponibleOrigen(BigDecimal saldoDisponibleOrigen) {
		this.saldoDisponibleOrigen = saldoDisponibleOrigen;
	}

	@Column(name = "OBSERVACION", length = 140, columnDefinition = "nvarchar2")
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	@Column(name = "ESTADO_SOLICITUD", nullable = false, precision = 22, scale = 0)
	public boolean getEstadoSolicitud() {
		return (this.estadoSolicitud == 1 ? true : false);
	}

	public void setEstadoSolicitud(boolean estadoSolicitud) {
		this.estadoSolicitud = (estadoSolicitud ? 1 : 0);
	}

	@Column(name = "ESTADO_CONFIRMACION", nullable = false, precision = 22, scale = 0)
	public boolean getEstadoConfirmacion() {
		return (this.estadoConfirmacion == 1 ? true : false);
	}

	public void setEstadoConfirmacion(boolean estadoConfirmacion) {
		this.estadoConfirmacion = (estadoConfirmacion ? 1 : 0);
	}

	@Column(name = "SALDO_DISPONIBLE_DESTINO", nullable = false, precision = 18)
	public BigDecimal getSaldoDisponibleDestino() {
		return this.saldoDisponibleDestino;
	}

	public void setSaldoDisponibleDestino(BigDecimal saldoDisponibleDestino) {
		this.saldoDisponibleDestino = saldoDisponibleDestino;
	}

	@Column(name = "MONTO", nullable = false, precision = 18)
	public BigDecimal getMonto() {
		return monto;
	}

	public void setMonto(BigDecimal monto) {
		this.monto = monto;
	}

}
