package org.sistemafinanciero.entity;

// Generated 02-may-2014 11:48:28 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Date;

/**
 * CuentaBancaria generated by hbm2java
 */

public class CuentaBancaria implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	public final static String findByNumeroCuenta = "CuentaBancaria.findByNumeroCuenta";

	private BigInteger idCuentaBancaria;
	private Socio socio;
	private TipoCuentaBancaria tipoCuentaBancaria;
	private String numeroCuenta;
	private String moneda;
	private Date fechaApertura;
	private Date fechaCierre;
	private BigDecimal saldo;
	private int cantidadRetirantes;
	private EstadoCuentaBancaria estado;

	public CuentaBancaria() {
	}

}
