package org.sistemafinanciero.entity;

// Generated 02-may-2014 11:48:28 by Hibernate Tools 4.0.0

import java.math.BigInteger;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Socio generated by hbm2java
 */

public class Socio implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private BigInteger idSocio;
	private String tipoDocumento;
	private String numeroDocumento;
	private TipoPersona tipoPersona;
	private String tipoDocumentoApoderado;
	private String numeroDocumentoApoderado;
	private CuentaAporte cuentaAporte;
	private Date fechaInicio;
	private Date fechaFin;
	private int estado;
	private Set cuentaBancarias = new HashSet(0);

	public Socio() {
	}

	

}
