package org.model.dao;

// Generated 16/08/2014 01:49:33 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Moneda generated by hbm2java
 */
@Entity
@Table(name = "MONEDA", schema = "AIR_COMMAND", uniqueConstraints = @UniqueConstraint(columnNames = {
		"DENOMINACION", "SIMBOLO" }))
public class Moneda implements java.io.Serializable {

	private BigDecimal idMoneda;
	private String simbolo;
	private String denominacion;
	private Set valorTasaIntereses = new HashSet(0);
	private Set tasaCambiosForIdMonedaDestino = new HashSet(0);
	private Set tasaCambiosForIdMonedaOrigen = new HashSet(0);

	public Moneda() {
	}

	public Moneda(BigDecimal idMoneda) {
		this.idMoneda = idMoneda;
	}

	public Moneda(BigDecimal idMoneda, String simbolo, String denominacion,
			Set valorTasaIntereses, Set tasaCambiosForIdMonedaDestino,
			Set tasaCambiosForIdMonedaOrigen) {
		this.idMoneda = idMoneda;
		this.simbolo = simbolo;
		this.denominacion = denominacion;
		this.valorTasaIntereses = valorTasaIntereses;
		this.tasaCambiosForIdMonedaDestino = tasaCambiosForIdMonedaDestino;
		this.tasaCambiosForIdMonedaOrigen = tasaCambiosForIdMonedaOrigen;
	}

	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "sequence_moneda")
	@SequenceGenerator(name = "sequence_moneda")
	@Id
	@Column(name = "ID_MONEDA", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdMoneda() {
		return this.idMoneda;
	}

	public void setIdMoneda(BigDecimal idMoneda) {
		this.idMoneda = idMoneda;
	}

	@Column(name = "SIMBOLO", length = 5)
	public String getSimbolo() {
		return this.simbolo;
	}

	public void setSimbolo(String simbolo) {
		this.simbolo = simbolo;
	}

	@Column(name = "DENOMINACION", length = 30)
	public String getDenominacion() {
		return this.denominacion;
	}

	public void setDenominacion(String denominacion) {
		this.denominacion = denominacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "moneda")
	public Set<ValorTasaInteres> getValorTasaIntereses() {
		return this.valorTasaIntereses;
	}

	public void setValorTasaIntereses(Set valorTasaIntereses) {
		this.valorTasaIntereses = valorTasaIntereses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "monedaByIdMonedaDestino")
	public Set<TasaCambio> getTasaCambiosForIdMonedaDestino() {
		return this.tasaCambiosForIdMonedaDestino;
	}

	public void setTasaCambiosForIdMonedaDestino(
			Set tasaCambiosForIdMonedaDestino) {
		this.tasaCambiosForIdMonedaDestino = tasaCambiosForIdMonedaDestino;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "monedaByIdMonedaOrigen")
	public Set<TasaCambio> getTasaCambiosForIdMonedaOrigen() {
		return this.tasaCambiosForIdMonedaOrigen;
	}

	public void setTasaCambiosForIdMonedaOrigen(Set tasaCambiosForIdMonedaOrigen) {
		this.tasaCambiosForIdMonedaOrigen = tasaCambiosForIdMonedaOrigen;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((simbolo == null) ? 0 : simbolo.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Moneda other = (Moneda) obj;
		if (simbolo == null) {
			if (other.simbolo != null)
				return false;
		} else if (!simbolo.equals(other.simbolo))
			return false;
		return true;
	}

}
