package org.model.dao;

// Generated 16/08/2014 01:49:33 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Servicio generated by hbm2java
 */
@Entity
@Table(name = "SERVICIO")
@GenericGenerator(name = "wikiSequenceGenerator", strategy = "org.hibernate.id.enhanced.SequenceStyleGenerator", parameters = {
		@Parameter(name = "prefer_sequence_per_entity", value = "true"),
		@Parameter(name = "optimizer ", value = "hilo") })
public class Servicio implements java.io.Serializable {

	private BigDecimal idServicio;
	private TipoServicio tipoServicio;
	private String denominacion;
	private String descripcion;
	private Set valorTasaIntereses = new HashSet(0);

	public Servicio() {
	}

	public Servicio(BigDecimal idServicio, TipoServicio tipoServicio,
			String denominacion) {
		this.idServicio = idServicio;
		this.tipoServicio = tipoServicio;
		this.denominacion = denominacion;
	}

	public Servicio(BigDecimal idServicio, TipoServicio tipoServicio,
			String denominacion, String descripcion, Set valorTasaIntereses) {
		this.idServicio = idServicio;
		this.tipoServicio = tipoServicio;
		this.denominacion = denominacion;
		this.descripcion = descripcion;
		this.valorTasaIntereses = valorTasaIntereses;
	}

	@Id
	@GeneratedValue(generator = "wikiSequenceGenerator")
	@Column(name = "ID_SERVICIO", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdServicio() {
		return this.idServicio;
	}

	public void setIdServicio(BigDecimal idServicio) {
		this.idServicio = idServicio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_TIPO_SERVICIO", nullable = false)
	public TipoServicio getTipoServicio() {
		return this.tipoServicio;
	}

	public void setTipoServicio(TipoServicio tipoServicio) {
		this.tipoServicio = tipoServicio;
	}

	@Column(name = "DENOMINACION", nullable = false, length = 30)
	public String getDenominacion() {
		return this.denominacion;
	}

	public void setDenominacion(String denominacion) {
		this.denominacion = denominacion;
	}

	@Column(name = "DESCRIPCION", length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "servicio")
	public Set<ValorTasaInteres> getValorTasaIntereses() {
		return this.valorTasaIntereses;
	}

	public void setValorTasaIntereses(Set valorTasaIntereses) {
		this.valorTasaIntereses = valorTasaIntereses;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((denominacion == null) ? 0 : denominacion.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Servicio other = (Servicio) obj;
		if (denominacion == null) {
			if (other.denominacion != null)
				return false;
		} else if (!denominacion.equals(other.denominacion))
			return false;
		return true;
	}

}
