package org.model.dao;

// Generated 16/08/2014 01:49:33 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TasaCambio generated by hbm2java
 */
@Entity
@Table(name = "TASA_CAMBIO")
public class TasaCambio implements java.io.Serializable {

	private BigDecimal idTasaCambio;
	private Moneda monedaByIdMonedaDestino;
	private Moneda monedaByIdMonedaOrigen;
	private BigDecimal valor;
	private String operacion;

	public TasaCambio() {
	}

	public TasaCambio(BigDecimal idTasaCambio, Moneda monedaByIdMonedaDestino,
			Moneda monedaByIdMonedaOrigen, BigDecimal valor, String operacion) {
		this.idTasaCambio = idTasaCambio;
		this.monedaByIdMonedaDestino = monedaByIdMonedaDestino;
		this.monedaByIdMonedaOrigen = monedaByIdMonedaOrigen;
		this.valor = valor;
		this.operacion = operacion;
	}

	@Id
	@Column(name = "ID_TASA_CAMBIO", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdTasaCambio() {
		return this.idTasaCambio;
	}

	public void setIdTasaCambio(BigDecimal idTasaCambio) {
		this.idTasaCambio = idTasaCambio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_MONEDA_DESTINO", nullable = false)
	public Moneda getMonedaByIdMonedaDestino() {
		return this.monedaByIdMonedaDestino;
	}

	public void setMonedaByIdMonedaDestino(Moneda monedaByIdMonedaDestino) {
		this.monedaByIdMonedaDestino = monedaByIdMonedaDestino;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_MONEDA_ORIGEN", nullable = false)
	public Moneda getMonedaByIdMonedaOrigen() {
		return this.monedaByIdMonedaOrigen;
	}

	public void setMonedaByIdMonedaOrigen(Moneda monedaByIdMonedaOrigen) {
		this.monedaByIdMonedaOrigen = monedaByIdMonedaOrigen;
	}

	@Column(name = "VALOR", nullable = false, precision = 6, scale = 4)
	public BigDecimal getValor() {
		return this.valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

	@Column(name = "OPERACION", nullable = false, length = 6)
	public String getOperacion() {
		return this.operacion;
	}

	public void setOperacion(String operacion) {
		this.operacion = operacion;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime
				* result
				+ ((monedaByIdMonedaDestino == null) ? 0
						: monedaByIdMonedaDestino.hashCode());
		result = prime
				* result
				+ ((monedaByIdMonedaOrigen == null) ? 0
						: monedaByIdMonedaOrigen.hashCode());
		result = prime * result
				+ ((operacion == null) ? 0 : operacion.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		TasaCambio other = (TasaCambio) obj;
		if (monedaByIdMonedaDestino == null) {
			if (other.monedaByIdMonedaDestino != null)
				return false;
		} else if (!monedaByIdMonedaDestino
				.equals(other.monedaByIdMonedaDestino))
			return false;
		if (monedaByIdMonedaOrigen == null) {
			if (other.monedaByIdMonedaOrigen != null)
				return false;
		} else if (!monedaByIdMonedaOrigen.equals(other.monedaByIdMonedaOrigen))
			return false;
		if (operacion == null) {
			if (other.operacion != null)
				return false;
		} else if (!operacion.equals(other.operacion))
			return false;
		return true;
	}

}
