package org.model.dao;

// Generated 16/08/2014 01:49:33 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoServicio generated by hbm2java
 */
@Entity
@Table(name = "TIPO_SERVICIO")
public class TipoServicio implements java.io.Serializable {

	private BigDecimal idTipoServicio;
	private String denominacion;
	private String descripcion;
	private Set servicios = new HashSet(0);

	public TipoServicio() {
	}

	public TipoServicio(BigDecimal idTipoServicio, String denominacion) {
		this.idTipoServicio = idTipoServicio;
		this.denominacion = denominacion;
	}

	public TipoServicio(BigDecimal idTipoServicio, String denominacion,
			String descripcion, Set servicios) {
		this.idTipoServicio = idTipoServicio;
		this.denominacion = denominacion;
		this.descripcion = descripcion;
		this.servicios = servicios;
	}

	@Id
	@Column(name = "ID_TIPO_SERVICIO", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdTipoServicio() {
		return this.idTipoServicio;
	}

	public void setIdTipoServicio(BigDecimal idTipoServicio) {
		this.idTipoServicio = idTipoServicio;
	}

	@Column(name = "DENOMINACION", nullable = false, length = 30)
	public String getDenominacion() {
		return this.denominacion;
	}

	public void setDenominacion(String denominacion) {
		this.denominacion = denominacion;
	}

	@Column(name = "DESCRIPCION", length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoServicio")
	public Set<Servicio> getServicios() {
		return this.servicios;
	}

	public void setServicios(Set servicios) {
		this.servicios = servicios;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((denominacion == null) ? 0 : denominacion.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		TipoServicio other = (TipoServicio) obj;
		if (denominacion == null) {
			if (other.denominacion != null)
				return false;
		} else if (!denominacion.equals(other.denominacion))
			return false;
		return true;
	}

}
