package org.softgreen.entity;

// Generated 02-may-2014 11:48:28 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.math.BigInteger;

/**
 * CuentaAporte generated by hbm2java
 */

public class CuentaAporte implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private BigInteger idCuentaaporte;
	private String numeroCuenta;
	private BigDecimal saldo;
	private String moneda;
	private EstadoCuentaAporte estadoCuenta;
	private Socio socio;

	public CuentaAporte() {
	}

}
