package org.softgreen.entity;

// Generated 02-may-2014 11:48:28 by Hibernate Tools 4.0.0

import java.math.BigDecimal;

/**
 * CuentaBancariaTasa generated by hbm2java
 */

public class CuentaBancariaTasa implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private String nombreTasa;
	private CuentaBancaria cuentaBancaria;
	private BigDecimal valor;

	public CuentaBancariaTasa() {
	}

}
