package org.softgreen.entity;

// Generated 02-may-2014 11:48:28 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Socio generated by hbm2java
 */

public class Socio implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private Long id;
	private TipoPersona tipoPersona;
	private String tipoDocumento;
	private String numeroDocumento;
	private String tipoDocumentoApoderado;
	private String numeroDocumentoApoderado;
	private Date fechaInicio;
	private Date fechaFin;
	private boolean estado;

	private CuentaAporte cuentaAporte;
	private Set<CuentaBancaria> cuentasBancarias = new HashSet<CuentaBancaria>(0);

	public Socio() {
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public TipoPersona getTipoPersona() {
		return tipoPersona;
	}

	public void setTipoPersona(TipoPersona tipoPersona) {
		this.tipoPersona = tipoPersona;
	}

	public String getTipoDocumento() {
		return tipoDocumento;
	}

	public void setTipoDocumento(String tipoDocumento) {
		this.tipoDocumento = tipoDocumento;
	}

	public String getNumeroDocumento() {
		return numeroDocumento;
	}

	public void setNumeroDocumento(String numeroDocumento) {
		this.numeroDocumento = numeroDocumento;
	}

	public String getTipoDocumentoApoderado() {
		return tipoDocumentoApoderado;
	}

	public void setTipoDocumentoApoderado(String tipoDocumentoApoderado) {
		this.tipoDocumentoApoderado = tipoDocumentoApoderado;
	}

	public String getNumeroDocumentoApoderado() {
		return numeroDocumentoApoderado;
	}

	public void setNumeroDocumentoApoderado(String numeroDocumentoApoderado) {
		this.numeroDocumentoApoderado = numeroDocumentoApoderado;
	}

	public Date getFechaInicio() {
		return fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public Date getFechaFin() {
		return fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	public boolean isEstado() {
		return estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

	public CuentaAporte getCuentaAporte() {
		return cuentaAporte;
	}

	public void setCuentaAporte(CuentaAporte cuentaAporte) {
		this.cuentaAporte = cuentaAporte;
	}

	public Set<CuentaBancaria> getCuentasBancarias() {
		return cuentasBancarias;
	}

	public void setCuentasBancarias(Set<CuentaBancaria> cuentasBancarias) {
		this.cuentasBancarias = cuentasBancarias;
	}

}
