package org.model;

// Generated 16/08/2014 01:49:33 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ForeignKey;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * ValorTasaInteres generated by hbm2java
 */
@Entity
@Table(name = "VALOR_TASA_INTERES")
public class ValorTasaInteres implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private Long idValorTasaInteres;
	private TasaInteres tasaInteres;
	private Moneda moneda;
	private Servicio servicio;
	private Date fechaInicio;
	private Date fechaFin;
	private BigDecimal montoMinimo;
	private BigDecimal montoMaximo;
	private BigDecimal periodoMinimo;
	private BigDecimal periodoMaximo;
	private BigDecimal valor;

	private Date version;

	public ValorTasaInteres() {
	}

	@Id
	@GeneratedValue(generator = "SequenceStyleGenerator")
	@Column(name = "ID_VALOR_TASA_INTERES", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getIdValorTasaInteres() {
		return this.idValorTasaInteres;
	}

	public void setIdValorTasaInteres(Long idValorTasaInteres) {
		this.idValorTasaInteres = idValorTasaInteres;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_TASA_INTERES", nullable = false, foreignKey = @ForeignKey)
	public TasaInteres getTasaInteres() {
		return this.tasaInteres;
	}

	public void setTasaInteres(TasaInteres tasaInteres) {
		this.tasaInteres = tasaInteres;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_MONEDA", nullable = false, foreignKey = @ForeignKey)
	public Moneda getMoneda() {
		return this.moneda;
	}

	public void setMoneda(Moneda moneda) {
		this.moneda = moneda;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_SERVICIO", nullable = false, foreignKey = @ForeignKey)
	public Servicio getServicio() {
		return this.servicio;
	}

	public void setServicio(Servicio servicio) {
		this.servicio = servicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_INICIO", length = 7)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_FIN", length = 7)
	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	@Column(name = "MONTO_MINIMO", precision = 22)
	public BigDecimal getMontoMinimo() {
		return this.montoMinimo;
	}

	public void setMontoMinimo(BigDecimal montoMinimo) {
		this.montoMinimo = montoMinimo;
	}

	@Column(name = "MONTO_MAXIMO", precision = 22)
	public BigDecimal getMontoMaximo() {
		return this.montoMaximo;
	}

	public void setMontoMaximo(BigDecimal montoMaximo) {
		this.montoMaximo = montoMaximo;
	}

	@Column(name = "PERIODO_MINIMO", precision = 22, scale = 0)
	public BigDecimal getPeriodoMinimo() {
		return this.periodoMinimo;
	}

	public void setPeriodoMinimo(BigDecimal periodoMinimo) {
		this.periodoMinimo = periodoMinimo;
	}

	@Column(name = "PERIODO_MAXIMO", precision = 22, scale = 0)
	public BigDecimal getPeriodoMaximo() {
		return this.periodoMaximo;
	}

	public void setPeriodoMaximo(BigDecimal periodoMaximo) {
		this.periodoMaximo = periodoMaximo;
	}

	@Column(name = "VALOR", precision = 22, scale = 3)
	public BigDecimal getValor() {
		return this.valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

	@Version
	@Temporal(value = TemporalType.TIMESTAMP)
	@Column(name = "OPTLOCK")
	public Date getVersion() {
		return this.version;
	}

	public void setVersion(Date version) {
		this.version = version;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime
				* result
				+ ((idValorTasaInteres == null) ? 0 : idValorTasaInteres
						.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ValorTasaInteres other = (ValorTasaInteres) obj;
		if (idValorTasaInteres == null) {
			if (other.idValorTasaInteres != null)
				return false;
		} else if (!idValorTasaInteres.equals(other.idValorTasaInteres))
			return false;
		return true;
	}

}
